### ISSUE TITLE
作者您好,如何推送非master分支下的文件呢?

### ISSUE THREAD

**Issue by Difers** [zkqiang/tencent-cos-action#2]
我的博客静态存放于非master分支下,我想在使用coscmd上传时选用该分支该怎么办呢?

**Comment by zkqiang** [comment]
```
on:
  push:
    branches:
      - master
```

master 改成你的分支
